spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  h2:
    console:
      enabled: true
#    show-sql: true

logging:
  level:
    org.hibernate.orm.jdbc.bind: trace
