spring:
  datasource:
    username: bookadmin
    password: password
    url: jdbc:mysql://127.0.0.1:3306/bookdb?useUnicode=true&character=UTF-8&serverTimezone=UTC
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update